### ISSUE TITLE
Dependency Version Pinning

### ISSUE THREAD

**Issue by ietz** [pdrm83/Py2Opt#4]
Hey @pdrm83 and thank you very much for open sourcing your code!

One small thing I noticed while using it is that you pin exact package versions of your dependencies in your `setup.py`, such as `numpy==1.20.0`. This can obviously cause conflicts in environments with other dependencies. Looking at the code, it seems to me that the internals should be quite flexible wrt. the installed versions. Would you mind relaxing the dependencies?

In my case, I have installed the newest version of Tensorflow (v2.5.0) next to py2opt. Tensorflow requires `numpy~=1.19.2`, which is incompatible with the py2opt dependency of `numpy==1.20.0`.

**Comment by pdrm83** [comment]
Hi @ietz. Thanks for your message. I relaxed the dependencies on `numpy` since, as you said, there is no need to be fixed. You can download the updated package from PyPi server now. Please let me know whether this resolves your issue. Thanks.

**Comment by ietz** [comment]
Thank you for the quick response and fix! I can confirm that the new version does resolve the dependency conflicts I encountered in my environment
